server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/art_share
    username: mnmr1996development
    password: mnmr1996development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false